# Generated by Django 5.0.3 on 2024-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("telegram_id", models.CharField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
