# Generated by Django 5.0.3 on 2024-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="correct_answer",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
