# Generated by Django 5.0.3 on 2024-03-23 10:36

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_subject_taskgroup_task_tasksolutionattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("name", models.CharField(primary_key=True, serialize=False)),
                ("tasks", models.ManyToManyField(to="api.task")),
            ],
        ),
        migrations.CreateModel(
            name="TestSolutionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.test"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="test_attempts",
            field=models.ManyToManyField(to="api.testsolutionattempt"),
        ),
        migrations.DeleteModel(
            name="TaskSolutionAttempt",
        ),
    ]
