# Generated by Django 5.0.3 on 2024-03-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasknumber",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tasknumber",
            name="number",
            field=models.IntegerField(unique=True),
        ),
    ]
