# Generated by Django 5.0.3 on 2024-03-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_tasknumber_name_alter_tasknumber_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="subject",
        ),
        migrations.AddField(
            model_name="tasknumber",
            name="subject",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.subject"
            ),
            preserve_default=False,
        ),
    ]
