# Generated by Django 5.0.3 on 2024-03-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_number",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="TaskGroup",
        ),
    ]
