# Generated by Django 5.0.3 on 2024-03-23 13:38

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_task_subject_tasknumber_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="answers",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, size=None
            ),
        ),
    ]
