# Generated by Django 5.0.3 on 2024-03-23 13:40

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_task_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="answers",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
