# Generated by Django 5.0.3 on 2024-03-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_task_task_number_delete_taskgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="task_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.tasknumber"
            ),
        ),
    ]
