# Generated by Django 5.0.3 on 2024-03-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tasknumber_alter_task_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumber',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
