# Generated by Django 5.0.3 on 2024-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_test_tasks_test_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("num_unordered", "Num Unordered"),
                    ("num_ordered", "Num Ordered"),
                    ("single_choice", "Single Choice"),
                ],
                default="text",
                max_length=255,
            ),
        ),
    ]
