# Generated by Django 5.0.3 on 2024-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_task_task_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предметы"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задание", "verbose_name_plural": "Задания"},
        ),
        migrations.AlterModelOptions(
            name="tasknumber",
            options={
                "verbose_name": "Номер задания",
                "verbose_name_plural": "Номера заданий",
            },
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "Тест", "verbose_name_plural": "Тесты"},
        ),
        migrations.AlterModelOptions(
            name="testsolutionattempt",
            options={
                "verbose_name": "Попытка решения",
                "verbose_name_plural": "Попытки решений",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
