# Generated by Django 5.0.3 on 2024-03-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_task_task_type_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolutionattempt",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="api.client"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("num_unordered", "Num Unordered"),
                    ("num_ordered", "Num Ordered"),
                    ("single_choice", "Single Choice"),
                ],
                default="text",
                max_length=255,
            ),
        ),
    ]
