# Generated by Django 5.0.3 on 2024-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_testsolutionattempt_user_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsolutionattempt",
            name="answers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
