# Generated by Django 5.0.3 on 2024-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_testsolutionattempt_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsolutionattempt",
            name="rating",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
