# Generated by Django 5.0.3 on 2024-03-23 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_testsolutionattempt_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="test_attempts",
        ),
    ]
